version: '3.8'
services:
  configsvr:
    image: mongo:6.0
    command: mongod --configsvr --replSet configReplSet --port 27019
    ports:
      - 27019:27019
    volumes:
      - configsvr_data:/data/db

  shard1_primary:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - 27020:27018
    volumes:
      - shard1_primary_data:/data/db

  shard1_secondary1:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - 27021:27018
    volumes:
      - shard1_secondary1_data:/data/db

  shard1_secondary2:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - 27022:27018
    volumes:
      - shard1_secondary2_data:/data/db

  shard2_primary:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018
    ports:
      - 27023:27018
    volumes:
      - shard2_primary_data:/data/db

  shard2_secondary1:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018
    ports:
      - 27024:27018
    volumes:
      - shard2_secondary1_data:/data/db

  shard2_secondary2:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018
    ports:
      - 27025:27018
    volumes:
      - shard2_secondary2_data:/data/db

  mongos:
    image: mongo:6.0
    command: mongos --configdb configReplSet/configsvr:27019 --bind_ip_all
    ports:
      - 27017:27017

volumes:
  configsvr_data:
  shard1_primary_data:
  shard1_secondary1_data:
  shard1_secondary2_data:
  shard2_primary_data:
  shard2_secondary1_data:
  shard2_secondary2_data: