version: '3.8'
services:
  configsvr:
    image: mongo:6.0
    command: mongod --configsvr --replSet configReplSet --port 27019
    ports:
      - 27019:27019
    volumes:
      - configsvr_data:/data/db
  shard1:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - 27020:27018
    volumes:
      - shard1_data:/data/db
  shard2:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018
    ports:
      - 27021:27018
    volumes:
      - shard2_data:/data/db
  mongos:
    image: mongo:6.0
    command: mongos --configdb configReplSet/configsvr:27019 --bind_ip_all
    ports:
      - 27017:27017
volumes:
  configsvr_data:
  shard1_data:
  shard2_data: